FROM node:18 as build

WORKDIR /app

COPY mascotas-frontend/package*.json ./
RUN npm install

COPY mascotas-frontend/src ./src
COPY mascotas-frontend/angular.json ./
COPY mascotas-frontend/tsconfig*.json ./

RUN npm run build:prod

FROM nginx:alpine

COPY --from=build /app/dist/mascotas-frontend /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
